# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

PYTHON_COMPAT=( python3_{11..13} )

DISTUTILS_USE_PEP517=setuptools
inherit distutils-r1 pypi

DESCRIPTION="Transform Python source code into it's most compact representation"

HOMEPAGE="https://github.com/dflook/python-minifier"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/39/63/403fb2d6394b3e455e046d91f64b96072803aaf119027a26e716ed94d63c/python_minifier-2.11.3.tar.gz"
RESTRICT="test"
KEYWORDS="amd64 arm arm64 x86"

SLOT="0"

IUSE=""

IUSE="test"
RESTRICT="!test? ( test )"

#DOCS="README.rst"

distutils_enable_tests pytest

#src_unpack() {
#	unpack ${A}
#	echo ${P}
#	mv python_minifier-2.11.3 python-minifier-2.11.3
#}
